//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Employee
{
    public int EmployeeId { get; set; }
    public string EmployeeName { get; set; }
    public string EmployeeImage { get; set; }
    public string EmployeeTitles { get; set; }
    public string EmployeeResume01 { get; set; }
    public string EmployeeResume02 { get; set; }
    public string EmployeeResume03 { get; set; }
    public string EmployeeResume04 { get; set; }
    public string EmployeeResume05 { get; set; }
    public string EmployeeResume06 { get; set; }
    public string EmployeeResume07 { get; set; }
    public string EmployeeResume08 { get; set; }
    public string EmployeeResume09 { get; set; }
    public string EmployeeResume10 { get; set; }
    public string EmployeeResume11 { get; set; }
    public string EmployeeResume12 { get; set; }
    public string EmployeeResume13 { get; set; }
    public string EmployeeResume14 { get; set; }
    public string EmployeeResume15 { get; set; }
    public string EmployeeResume16 { get; set; }
    public string EmployeeResume17 { get; set; }
    public string EmployeeResume18 { get; set; }
    public string EmployeeResume19 { get; set; }
    public string EmployeeResume20 { get; set; }
    public string EmployeeEmail { get; set; }
}

public partial class Index
{
    public int IndexId { get; set; }
    public int ProjectId { get; set; }
    public string projectImageIndex { get; set; }
    public string IndexCompanyTitle01 { get; set; }
    public string IndexCompanyTitle02 { get; set; }
    public string IndexDesignsText { get; set; }
    public string IndexPrincipalName { get; set; }
    public string IndexPrincipalImage { get; set; }
    public string IndexCompantEmail { get; set; }
    public string IndexCompantPhome { get; set; }
    public string IndexCompantAddress { get; set; }
    public string IndexSocialmediaName { get; set; }
    public string IndexSocialmediaUrl { get; set; }
}

public partial class Medium
{
    public int MediaId { get; set; }
    public string mediaImage { get; set; }
    public string mediaText1 { get; set; }
    public string mediaText2 { get; set; }
}

public partial class Project
{
    public int ProjectId { get; set; }
    public string projectImageIndex { get; set; }
    public string ProjectName1 { get; set; }
    public string ProjectName2 { get; set; }
    public string ProjectName3 { get; set; }
    public string ProjectTitle01 { get; set; }
    public string ProjectTitle02 { get; set; }
    public string ProjectTitle03 { get; set; }
    public string ProjectTitle04 { get; set; }
    public string ProjectText01 { get; set; }
    public string ProjectText02 { get; set; }
    public string ProjectText03 { get; set; }
    public string ProjectText04 { get; set; }
    public string ProjectDetal01 { get; set; }
    public string ProjectDetal02 { get; set; }
    public string ProjectDetal03 { get; set; }
    public string principalName { get; set; }
    public string principalImage { get; set; }
}

public partial class User
{
    public int UserId { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string Role { get; set; }
    public string UserName { get; set; }
    public string UserImage { get; set; }
}
